### ISSUE TITLE
[Improvement] File Upload Field on Form Instance

### ISSUE THREAD

**Issue by jgardner-qha** [Research-IT-Swiss-TPH/redcap-pdf-injector#17]
It'd be great to be able to specify a form upload field within the project per injection. Then, add a record save hook that would perform the injection, ideally merge/flatten the file, then upload the resulting PDF to the field on the record. This would make the PDF available immediately on a form or even a survey page without clicking through the injection screens.

A particular use-case would be a legal or medical survey where the anonymous end-user would complete details in a traditional REDCap survey, during which it would automatically fill fields on associated "paper" documents that need to be stored with the survey. Both the end-user and REDCap operators would have access to the same file as it was recorded at the time of the survey.

**Comment by tertek** [comment]
Please correct me if I got you wrong:
1) Per Injection there can be defined one or more fields that represent a mapping to a form/survey field.
2) After Data Entry/Survey Completion a "mapped field" (form upload field as you called) is triggered (on record save hook) to initiate an injection that will generate the PDF Document, save it to edocs and reference its ID into the field.
3) If the "mapped field" is filled with a valid document ID a Download Button can be used on Data Entry and/or Survey Page.

I agree that this can be a very useful scenario, but:
- Currently, flattening is not supported. I have researched a lot and could not find a non-commercial PHP library that does the job without being an additional OS layer dependency. Theoretically, pdftk could be installed on the server but this would be a challenge for a lot of environments with strict IT policies including our own.
- If there is no flattening, serving the "open" PDF to the external user is not good practice. Documents good be edited and faked at will.

With respect to this limitation, I would say it would not make sense to extend the module yet into this direction. Although I agree, that this is very needed and we also had thoughts of these kind.

**Comment by tertek** [comment]
@jgardner-qha I have added a new feature in version 3.0.0 that supports adding a download button through Action Tag to Data Entry Pages. For now I have not enabled this feature for Survey Pages, since the PDFs cannot be flattened, hence it is unsafe and not good practice to share these documents with participants.

As soon as there is a way to flatten PDFs (see posts above).
Feel free to re-open the issue any time.

**Comment by jgardner-qha** [comment]
Thank you! I'm looking forward to trying it!

In the meantime, for my specific use case, I developed a very limited module that fills a PDF template and then performs server-side flattening using pdftk. It's not perfect by any stretch but largely meets the requirements of one of our projects with non-sensitive data. I'll continue to watch for open source pure PHP/JS solutions for flattening and let you know if I find any.
