### ISSUE TITLE
Dokumentation Link

### ISSUE THREAD

**Issue by ThomasVermes** [Research-IT-Swiss-TPH/redcap-pdf-injector#32]
Oi Ekin =)

![image](https://user-images.githubusercontent.com/75424115/234851566-a0818e1a-25ff-4b4a-846c-d3eb9be49723.png)

das link in github funktioniert nicht mehr

lg
Thomas

**Comment by tertek** [comment]
Merci.

0ad778988adb4936db68b3c8a29c6f8bca639426
