### ISSUE TITLE
Field not detected in PDF created with external service

### ISSUE THREAD

**Issue by Natalia258** [Research-IT-Swiss-TPH/redcap-pdf-injector#42]
Hi, 
I have created a fillable pdf on the server sejda.com, then I used pdftk and the final version of the document I uploaded through the module. After upload there are no fields for filling but they were created in the document.
Thanks in advance.

**Comment by tertek** [comment]
@Natalia258 I am unable to give you support for third party pdf editors that I do not know, as sejda.com.
You could upload a test PDF created with sejda.com, so I may check what is the problem.

It is recommened to create PDFs with:

Adobe Acrobat Pro (Commercial) [Learn here how to create fillable pdf forms](https://acrobat.adobe.com/us/en/acrobat/how-to/create-fillable-pdf-forms-creator.html)
    LibreOffice Writer (Free) [Fillable PDF Forms With LibreOffice Writer](https://www.linuxuprising.com/2019/02/how-to-create-fillable-pdf-forms-with.html)

**Comment by Natalia258** [comment]
Thanks very much for replay.
I tried to create pdf with LibreOffice but my problem was that in the multiple line field if the answer is longer there is some of the text missing when printing document. 
I found this editor sejda.com which create fillable pdf in which when user type long answer text gets smaller and entire text is printed. When uploading this document through pdf injector none of the filed was recognized as fillable and the document seemed as no field was in it.

I am uploading a test PDF with 2 fields. 
[test.pdf](https://github.com/Research-IT-Swiss-TPH/redcap-pdf-injector/files/14555599/test.pdf)

**Comment by tertek** [comment]
@Natalia258 I have checked your test.pdf and can confirm that it does not work.
I was unable to identify the exact issue, but as I already said it is not possible to give further support for additional external services.
As far as I know you can setup multi-line fields in LibreOffice, maybe this thread can help you: 
https://ask.libreoffice.org/t/libreoffice-base-how-to-make-form-fields-show-text-properly/25541

I have attached a working multline PDF created with Adobe.

[pdftk_test_adobe.pdf](https://github.com/Research-IT-Swiss-TPH/redcap-pdf-injector/files/14555896/pdftk_test_adobe.pdf)

Please note that you may need to "free" your PDFs with pdftk, as explained in the documentation:
https://research-it-swiss-tph.github.io/redcap-pdf-injector/#requirements-and-limitations

Closing.
